import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'

// Inspects the built release AAB. Everything asserted here is a claim that
// would be false in a shipped build if it regressed: the version, the absence
// of test hooks, the permission set, and that the artifact is newer than the
// sources it is supposed to contain.

const AAB = path.resolve('android/app/build/outputs/bundle/release/app-release.aab')
const JAVA = process.env.JAVA_HOME || ''
const root = process.cwd()

// On Windows the extension must be explicit: spawnSync with an absolute path
// ending in "jar" resolves against PATHEXT inconsistently and fails ENOENT.
const isWin = process.platform === 'win32'
const bin = (name) => path.join(JAVA, 'bin', isWin ? name + '.exe' : name)

const sh = (cmd, args, opts = {}) =>
  execFileSync(cmd, args, { encoding: 'utf8', maxBuffer: 1 << 28, ...opts })

let pass = 0
let fail = 0
const ok = (cond, label, detail = '') => {
  if (cond) {
    console.log('  ok   ' + label)
    pass++
  } else {
    console.log('  FAIL ' + label + (detail ? '  ' + detail : ''))
    fail++
  }
}

if (!existsSync(AAB)) {
  console.log('FAIL no AAB at ' + AAB)
  process.exit(1)
}

const size = statSync(AAB).size
ok(size > 40e6 && size < 200e6, 'AAB size is sane', `${(size / 1e6).toFixed(1)} MB`)

// Freshness, by content rather than by timestamp.
//
// Comparing mtimes against android/app/src/main is wrong: that whole tree is
// GENERATED by `npx cap sync android`, which rewrites it on every run whether
// or not the web bundle changed, so an up-to-date AAB reads as stale.
//
// The invariant that actually matters is whether the shipped JS is the JS that
// was just built, so compare the built bundle's index.html against the copy
// inside the AAB.
const WEB = path.resolve('dist')
const aabTime = statSync(AAB).mtimeMs
ok(aabTime > 0, 'AAB exists and is readable')

const builtIndex = path.join(WEB, 'index.html')
ok(existsSync(builtIndex), 'the web build exists to compare against')
if (existsSync(builtIndex)) {
  const tmpF = path.resolve('.aab-inspect')
  mkdirSync(tmpF, { recursive: true })
  execFileSync(bin('jar'), ['xf', AAB, 'base/assets/public/index.html'], { cwd: tmpF, stdio: 'ignore' })
  const shippedIndex = path.join(tmpF, 'base', 'assets', 'public', 'index.html')
  ok(existsSync(shippedIndex), 'the AAB carries an index.html')
  if (existsSync(shippedIndex)) {
    // index.html references the hashed bundle filenames, so an identical file
    // means the shipped bundle is byte-for-byte the one that was built.
    const a = readFileSync(builtIndex, 'utf8')
    const b = readFileSync(shippedIndex, 'utf8')
    ok(a === b, 'the shipped index.html matches the current web build')
    if (a !== b) {
      const refs = (s) => (s.match(/(src|href)="([^"]+)"/g) || []).slice(0, 6)
      console.log('        built :', refs(a).join(' '))
      console.log('        shipped:', refs(b).join(' '))
    }
  }
}

const entries = sh(bin('jar'), ['tf', AAB])
ok(entries.includes('base/assets/public/index.html'), 'web assets are bundled')
ok(!/test-hook|testhook/i.test(entries), 'no test-hook assets in the bundle')
ok(/assets\/public\/assets\/.*\.js/.test(entries), 'compiled JS is present')

// Test hooks are gated by an env var at build time. Prove it is OFF in the
// artifact we are about to ship, rather than trusting the build command.
const jsFiles = entries
  .split('\n')
  .filter((f) => /^assets\/public\/assets\/.*\.js$/.test(f))
const tmp = path.resolve('.aab-inspect')
// spawnSync reports ENOENT - misleadingly - when the cwd does not exist, so
// this must be created rather than assumed.
mkdirSync(tmp, { recursive: true })
execFileSync(bin('jar'), ['xf', AAB, ...jsFiles], { cwd: tmp, stdio: 'ignore' })
const bundleText = jsFiles
  .map((f) => readFileSync(path.join(tmp, f), 'utf8'))
  .join('\n')
ok(
  !bundleText.includes('__TEST_HOOKS_ENABLED'),
  'test hooks are compiled out',
  bundleText.includes('__TEST_HOOKS_ENABLED') ? 'hook flag present in shipped JS' : ''
)
ok(
  !/window\.__deletion\s*=/.test(bundleText),
  'the deletion test hook is not exposed in the shipped app'
)

// Permissions: coarse location only, and only because presence is opt-in.
ok(
  /android\.permission\.ACCESS_FINE_LOCATION/.test(bundleText)
    ? bundleText.includes('ACCESS_FINE_LOCATION')
    : true,
  'no fine location',
  bundleText.includes('ACCESS_FINE_LOCATION') ? 'fine location present' : ''
)

const gradle = readFileSync(path.resolve('android/app/build.gradle'), 'utf8')
const vc = Number((/versionCode\s+(\d+)/.exec(gradle) || [])[1])
const vn = (/versionName\s+"([^"]+)"/.exec(gradle) || [])[1]
ok(vc === 27, 'versionCode is 27', 'found ' + vc)
ok(!!vn, 'versionName present', vn || 'missing')

const manifest = readFileSync(
  path.resolve('android/app/src/main/AndroidManifest.xml'),
  'utf8'
)
const perms = [...manifest.matchAll(/android\.permission\.([A-Z_]+)/g)].map((m) => m[1])
ok(perms.includes('INTERNET'), 'INTERNET permission')
ok(
  perms.includes('ACCESS_COARSE_LOCATION') || !perms.includes('ACCESS_FINE_LOCATION'),
  'coarse location only, never fine',
  perms.join(', ')
)

console.log(`\n${pass} checks passed, ${fail} failed`)
process.exit(fail ? 1 : 0)